### ISSUE TITLE
🚨 [Bug] I can't connect todolist search api between Frontend and Backend

### ISSUE THREAD

**Issue by orieasy1** [orieasy1/Time_To_Do#34]
## 🚨 Issue Checklist

- [x] Issue Title: [BUG] 'Detailed bug description'
- [ ] Add Assignees and Labels.

## 🐛 Bug Overview

- This bug has occurred.
- I can connect. Error comes out
![image](https://github.com/user-attachments/assets/0b9a2801-a7e4-44b5-ae76-dd5865c6d8a6)

## 🐞 Detailed Bug Description

- Steps to reproduce the bug: We schould check frontend and backends' json type 
- The problem seems to occur in this file or code section.

## ✅ TODO

- [x] To fix this, we need to do the following: Code review between teamates
- [ ] Also, this task might be required.

**Comment by seoha376** [comment]
We discussed hard about this topic, but it was difficult to solve at that time... The problem is worth to be talked together again!
